INSERT INTO Countries(EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('Afghanistan', 'Afganistan', 'AF', NULL, '^\+93\d{9}$', 'Kabul', 'Asia', 'Pashto, Dari', 'UTC+04:30', 'Afghani', 'AFN', '+93', 'Afghanistan is a landlocked country located in South Asia and Central Asia.'),
('Albania', 'Albania', 'AL', NULL, '^\+355\d{8,9}$', 'Tirana', 'Europe', 'Albanian', 'UTC+01:00', 'Lek', 'ALL', '+355', 'Albania is a country in Southeast Europe on the Adriatic and Ionian Sea within the Mediterranean.'),
('Algeria', 'Algieria', 'DZ', NULL, '^\+213\d{9}$', 'Algiers', 'Africa', 'Arabic', 'UTC+01:00', 'Algerian dinar', 'DZD', '+213', 'Algeria is a North African country with a Mediterranean coastline and a Saharan desert interior.'),
('Andorra', 'Andora', 'AD', NULL, '^\+376\d{6}$', 'Andorra la Vella', 'Europe', 'Catalan', 'UTC+01:00', 'Euro', 'EUR', '+376', 'Andorra is a tiny, independent principality situated between France and Spain in the Pyrenees mountains.'),
('Angola', 'Angola', 'AO', NULL, '^\+244\d{9}$', 'Luanda', 'Africa', 'Portuguese', 'UTC+01:00', 'Kwanza', 'AOA', '+244', 'Angola is a Southern African nation with varied terrain encompassing tropical Atlantic beaches, a labyrinthine system of rivers and Sub-Saharan desert.'),
('Antigua and Barbuda', 'Antigua i Barbuda', 'AG', NULL, '^\+1-268\d{7}$', 'St. John''s', 'North America', 'English', 'UTC-04:00', 'East Caribbean dollar', 'XCD', '+1-268', 'Antigua and Barbuda is a country comprising two major islands and several smaller ones, known for its reef-lined beaches, rainforests, and resorts.'),
('Argentina', 'Argentyna', 'AR', NULL, '^\+54\d{10}$', 'Buenos Aires', 'South America', 'Spanish', 'UTC-03:00', 'Argentine peso', 'ARS', '+54', 'Argentina is a massive South American nation with terrain encompassing Andes mountains, glacial lakes and Pampas grassland.'),
('Armenia', 'Armenia', 'AM', NULL, '^\+374\d{8}$', 'Yerevan', 'Asia', 'Armenian', 'UTC+04:00', 'Armenian dram', 'AMD', '+374', 'Armenia is a nation, and former Soviet republic, in the mountainous Caucasus region between Asia and Europe.'),
('Australia', 'Australia', 'AU', NULL, '^\+61\d{9}$', 'Canberra', 'Australia', 'English', 'UTC+10:00', 'Australian dollar', 'AUD', '+61', 'Australia is a country and continent surrounded by the Indian and Pacific oceans.'),
('Austria', 'Austria', 'AT', NULL, '^\+43\d{10}$', 'Vienna', 'Europe', 'German', 'UTC+01:00', 'Euro', 'EUR', '+43', 'Austria is a German-speaking country in Central Europe, characterized by mountain villages, baroque architecture, Imperial history and rugged Alpine terrain.'),
('Azerbaijan', 'Azerbejdżan', 'AZ', NULL, '^\+994\d{9}$', 'Baku', 'Asia', 'Azerbaijani', 'UTC+04:00', 'Azerbaijani manat', 'AZN', '+994', 'Azerbaijan, the nation and former Soviet republic, is bounded by the Caspian Sea and Caucasus Mountains, which span Asia and Europe.'),
('Bahamas', 'Bahamy', 'BS', NULL, '^\+1-242\d{7}$', 'Nassau', 'North America', 'English', 'UTC-05:00', 'Bahamian dollar', 'BSD', '+1-242', 'The Bahamas is a coral-based archipelago in the Atlantic Ocean with 700-plus islands and cays, known for its beaches and offshore reef.'),
('Bahrain', 'Bahrajn', 'BH', NULL, '^\+973\d{8}$', 'Manama', 'Asia', 'Arabic', 'UTC+03:00', 'Bahraini dinar', 'BHD', '+973', 'Bahrain, a nation comprising more than 30 islands in the Persian Gulf, has been at the center of major trade routes since antiquity.'),
('Bangladesh', 'Bangladesz', 'BD', NULL, '^\+880\d{10}$', 'Dhaka', 'Asia', 'Bengali', 'UTC+06:00', 'Bangladeshi taka', 'BDT', '+880', 'Bangladesh, to the east of India on the Bay of Bengal, is a South Asian country marked by lush greenery and many waterways.'),
('Barbados', 'Barbados', 'BB', NULL, '^\+1-246\d{7}$', 'Bridgetown', 'North America', 'English', 'UTC-04:00', 'Barbadian dollar', 'BBD', '+1-246', 'Barbados is an eastern Caribbean island and an independent British Commonwealth nation.'),
('Belarus', 'Białoruś', 'BY', NULL, '^\+375\d{9}$', 'Minsk', 'Europe', 'Belarusian, Russian', 'UTC+03:00', 'Belarusian ruble', 'BYN', '+375', 'Belarus, a landlocked country in Eastern Europe, is known for its Stalinist architecture, grand fortifications and primeval forests.'),
('Belgium', 'Belgia', 'BE', NULL, '^\+32\d{8,9}$', 'Brussels', 'Europe', 'Dutch, French, German', 'UTC+01:00', 'Euro', 'EUR', '+32', 'Belgium, a country in Western Europe, is known for medieval towns, Renaissance architecture and as headquarters of the European Union and NATO.'),
('Belize', 'Belize', 'BZ', NULL, '^\+501\d{7}$', 'Belmopan', 'North America', 'English', 'UTC-06:00', 'Belize dollar', 'BZD', '+501', 'Belize is a nation on the eastern coast of Central America, with Caribbean Sea shorelines to the east and dense jungle to the west.'),
('Benin', 'Benin', 'BJ', NULL, '^\+229\d{8}$', 'Porto-Novo', 'Africa', 'French', 'UTC+01:00', 'West African CFA franc', 'XOF', '+229', 'Benin is a French-speaking West African nation, a birthplace of the vodun (or "voodoo") religion and home to the former Dahomey Kingdom from circa 1600–1900.'),
('Bhutan', 'Bhutan', 'BT', NULL, '^\+975\d{8}$', 'Thimphu', 'Asia', 'Dzongkha', 'UTC+06:00', 'Bhutanese ngultrum', 'BTN', '+975', 'Bhutan, a Buddhist kingdom on the Himalayas’ eastern edge, is known for its monasteries, fortresses (or dzongs) and dramatic landscapes.'),
('Bolivia', 'Boliwia', 'BO', NULL, '^\+591\d{8}$', 'Sucre', 'South America', 'Spanish, Quechua, Aymara', 'UTC-04:00', 'Boliviano', 'BOB', '+591', 'Bolivia is a country in central South America, with a varied terrain spanning Andes Mountains, the Atacama Desert and Amazon Basin rainforest.'),
('Bosnia and Herzegovina', 'Bośnia i Hercegowina', 'BA', NULL, '^\+387\d{8}$', 'Sarajevo', 'Europe', 'Bosnian, Croatian, Serbian', 'UTC+01:00', 'Convertible mark', 'BAM', '+387', 'Bosnia and Herzegovina is a country on the Balkan Peninsula in southeastern Europe.'),
('Botswana', 'Botswana', 'BW', NULL, '^\+267\d{8}$', 'Gaborone', 'Africa', 'English, Tswana', 'UTC+02:00', 'Botswana pula', 'BWP', '+267', 'Botswana, a landlocked country in Southern Africa, has a landscape defined by the Kalahari Desert and the Okavango Delta, which becomes a lush animal habitat during the seasonal floods.'),
('Brazil', 'Brazylia', 'BR', NULL, '^\+55\d{10,11}$', 'Brasília', 'South America', 'Portuguese', 'UTC-03:00', 'Brazilian real', 'BRL', '+55', 'Brazil, a vast South American country, stretches from the Amazon Basin in the north to vineyards and massive Iguaçu Falls in the south.'),
('Brunei', 'Brunei', 'BN', NULL, '^\+673\d{8}$', 'Bandar Seri Begawan', 'Asia', 'Malay', 'UTC+08:00', 'Brunei dollar', 'BND', '+673', 'Brunei is a tiny nation on the island of Borneo, in two distinct sections surrounded by Malaysia and the South China Sea.'),
('Bulgaria', 'Bułgaria', 'BG', NULL, '^\+359\d{9}$', 'Sofia', 'Europe', 'Bulgarian', 'UTC+02:00', 'Bulgarian lev', 'BGN', '+359', 'Bulgaria is a Balkan nation with diverse terrain encompassing Black Sea coastline, a mountainous interior and rivers, including the Danube.'),
('Burkina Faso', 'Burkina Faso', 'BF', NULL, '^\+226\d{8}$', 'Ouagadougou', 'Africa', 'French', 'UTC+00:00', 'West African CFA franc', 'XOF', '+226', 'Burkina Faso is a landlocked country in West Africa with a population of about 20.9 million.'),
('Burundi', 'Burundi', 'BI', NULL, '^\+257\d{8}$', 'Gitega', 'Africa', 'Kirundi, French', 'UTC+02:00', 'Burundian franc', 'BIF', '+257', 'Burundi, a landlocked country in East Africa, is known for its beautiful scenery, including beaches along Lake Tanganyika.'),
('Cabo Verde', 'Wyspy Zielonego Przylądka', 'CV', NULL, '^\+238\d{7}$', 'Praia', 'Africa', 'Portuguese', 'UTC-01:00', 'Cape Verdean escudo', 'CVE', '+238', 'Cabo Verde, or Cape Verde, is a nation on a volcanic archipelago off the northwest coast of Africa.'),
('Cambodia', 'Kambodża', 'KH', NULL, '^\+855\d{8,9}$', 'Phnom Penh', 'Asia', 'Khmer', 'UTC+07:00', 'Cambodian riel', 'KHR', '+855', 'Cambodia, located in Southeast Asia, is known for its temples, including Angkor Wat, and vibrant culture.')
;


INSERT INTO Countries (EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('Cameroon', 'Kamerun', 'CM', NULL, '^\+237\d{8}$', 'Yaoundé', 'Africa', 'French, English', 'UTC+01:00', 'Central African CFA franc', 'XAF', '+237', 'Cameroon, in Central Africa, is known for its diverse culture and geography, with beaches, deserts, mountains, rainforests, and savannas.'),
('Canada', 'Kanada', 'CA', NULL, '^\+1\d{10}$', 'Ottawa', 'North America', 'English, French', 'UTC-05:00 to UTC-08:00', 'Canadian dollar', 'CAD', '+1', 'Canada is a North American country stretching from the U.S. in the south to the Arctic Circle in the north.'),
('Central African Republic', 'Republika Środkowoafrykańska', 'CF', NULL, '^\+236\d{8}$', 'Bangui', 'Africa', 'French, Sango', 'UTC+01:00', 'Central African CFA franc', 'XAF', '+236', 'The Central African Republic is a landlocked country in Central Africa known for its biodiversity.'),
('Chad', 'Czad', 'TD', NULL, '^\+235\d{8}$', 'N''Djamena', 'Africa', 'French, Arabic', 'UTC+01:00', 'Central African CFA franc', 'XAF', '+235', 'Chad is a landlocked country in north-central Africa.'),
('Chile', 'Chile', 'CL', NULL, '^\+56\d{9}$', 'Santiago', 'South America', 'Spanish', 'UTC-04:00', 'Chilean peso', 'CLP', '+56', 'Chile, a long, narrow country stretching along South America''s western edge, has over 6,000km of Pacific Ocean coastline.'),
('China', 'Chiny', 'CN', NULL, '^\+86\d{11}$', 'Beijing', 'Asia', 'Mandarin', 'UTC+08:00', 'Renminbi (Yuan)', 'CNY', '+86', 'China, a populous nation in East Asia, is known for its vast landscape and history.'),
('Colombia', 'Kolumbia', 'CO', NULL, '^\+57\d{10}$', 'Bogotá', 'South America', 'Spanish', 'UTC-05:00', 'Colombian peso', 'COP', '+57', 'Colombia, located at the northern tip of South America, is known for its rainforests, Andes mountains, and coffee plantations.'),
('Comoros', 'Komory', 'KM', NULL, '^\+269\d{7}$', 'Moroni', 'Africa', 'Comorian, Arabic, French', 'UTC+03:00', 'Comorian franc', 'KMF', '+269', 'The Comoros is a volcanic archipelago off Africa’s east coast, in the warm Indian Ocean waters of the Mozambique Channel.'),
('Congo, Democratic Republic of the', 'Demokratyczna Republika Konga', 'CD', NULL, '^\+243\d{9}$', 'Kinshasa', 'Africa', 'French', 'UTC+01:00 to UTC+02:00', 'Congolese franc', 'CDF', '+243', 'The Democratic Republic of the Congo, also known as DR Congo, is a country in Central Africa.'),
('Congo, Republic of the', 'Republika Konga', 'CG', NULL, '^\+242\d{9}$', 'Brazzaville', 'Africa', 'French', 'UTC+01:00', 'Central African CFA franc', 'XAF', '+242', 'The Republic of the Congo, also known as Congo-Brazzaville, is a country in Central Africa.'),
('Costa Rica', 'Kostaryka', 'CR', NULL, '^\+506\d{8}$', 'San José', 'North America', 'Spanish', 'UTC-06:00', 'Costa Rican colón', 'CRC', '+506', 'Costa Rica is a rugged, rainforested Central American country with coastlines on the Caribbean and Pacific.'),
('Croatia', 'Chorwacja', 'HR', NULL, '^\+385\d{8,9}$', 'Zagreb', 'Europe', 'Croatian', 'UTC+01:00', 'Croatian kuna', 'HRK', '+385', 'Croatia, an Eastern European country, has a long coastline on the Adriatic Sea.'),
('Cuba', 'Kuba', 'CU', NULL, '^\+53\d{8}$', 'Havana', 'North America', 'Spanish', 'UTC-05:00', 'Cuban peso', 'CUP', '+53', 'Cuba is the largest island in the Caribbean, known for its white-sand beaches, rolling mountains, cigars and rum.'),
('Cyprus', 'Cypr', 'CY', NULL, '^\+357\d{8}$', 'Nicosia', 'Europe', 'Greek, Turkish', 'UTC+02:00', 'Euro', 'EUR', '+357', 'Cyprus is an island country in the Eastern Mediterranean known for its beaches and ancient ruins.'),
('Czech Republic', 'Czechy', 'CZ', NULL, '^\+420\d{9}$', 'Prague', 'Europe', 'Czech', 'UTC+01:00', 'Czech koruna', 'CZK', '+420', 'The Czech Republic, in Central Europe, is known for its ornate castles, native beers and long history.'),
('Denmark', 'Dania', 'DK', NULL, '^\+45\d{8}$', 'Copenhagen', 'Europe', 'Danish', 'UTC+01:00', 'Danish krone', 'DKK', '+45', 'Denmark is a Scandinavian country comprising the Jutland Peninsula and numerous islands.'),
('Djibouti', 'Dżibuti', 'DJ', NULL, '^\+253\d{8}$', 'Djibouti', 'Africa', 'French, Arabic', 'UTC+03:00', 'Djiboutian franc', 'DJF', '+253', 'Djibouti is a country located in the Horn of Africa.'),
('Dominica', 'Dominika', 'DM', NULL, '^\+1-767\d{7}$', 'Roseau', 'North America', 'English', 'UTC-04:00', 'East Caribbean dollar', 'XCD', '+1-767', 'Dominica is a mountainous Caribbean island nation with natural hot springs and tropical rainforests.'),
('Dominican Republic', 'Dominikana', 'DO', NULL, '^\+1-809\d{7}$', 'Santo Domingo', 'North America', 'Spanish', 'UTC-04:00', 'Dominican peso', 'DOP', '+1-809', 'The Dominican Republic is a Caribbean nation that shares the island of Hispaniola with Haiti to the west.'),
('Ecuador', 'Ekwador', 'EC', NULL, '^\+593\d{8,9}$', 'Quito', 'South America', 'Spanish', 'UTC-05:00', 'United States dollar', 'USD', '+593', 'Ecuador is a country straddling the equator on South America’s west coast.'),
('Egypt', 'Egipt', 'EG', NULL, '^\+20\d{9}$', 'Cairo', 'Africa', 'Arabic', 'UTC+02:00', 'Egyptian pound', 'EGP', '+20', 'Egypt, a country linking northeast Africa with the Middle East, dates to the time of the pharaohs.'),
('El Salvador', 'Salwador', 'SV', NULL, '^\+503\d{8}$', 'San Salvador', 'North America', 'Spanish', 'UTC-06:00', 'United States dollar', 'USD', '+503', 'El Salvador, the smallest and the most densely populated country in Central America, is known for its Pacific Ocean beaches, surf spots and mountainous landscape.'),
('Equatorial Guinea', 'Gwinea Równikowa', 'GQ', NULL, '^\+240\d{8}$', 'Malabo', 'Africa', 'Spanish, French, Portuguese', 'UTC+01:00', 'Central African CFA franc', 'XAF', '+240', 'Equatorial Guinea is a Central African country comprising the Rio Muni mainland and 5 volcanic offshore islands.'),
('Eritrea', 'Erytrea', 'ER', NULL, '^\+291\d{7}$', 'Asmara', 'Africa', 'Tigrinya, Arabic, English', 'UTC+03:00', 'Eritrean nakfa', 'ERN', '+291', 'Eritrea is a Northeast African country on the Red Sea coast.'),
('Estonia', 'Estonia', 'EE', NULL, '^\+372\d{7,8}$', 'Tallinn', 'Europe', 'Estonian', 'UTC+02:00', 'Euro', 'EUR', '+372', 'Estonia, a country in Northern Europe, borders the Baltic Sea and Gulf of Finland.'),
('Eswatini', 'Eswatini', 'SZ', NULL, '^\+268\d{8}$', 'Mbabane', 'Africa', 'Swazi, English', 'UTC+02:00', 'Swazi lilangeni', 'SZL', '+268', 'Eswatini, formerly Swaziland, is a landlocked country in Southern Africa known for its wilderness reserves and festivals.'),
('Ethiopia', 'Etiopia', 'ET', NULL, '^\+251\d{9}$', 'Addis Ababa', 'Africa', 'Amharic', 'UTC+03:00', 'Ethiopian birr', 'ETB', '+251', 'Ethiopia, in the Horn of Africa, is a rugged, landlocked country split by the Great Rift Valley.'),
('Fiji', 'Fidżi', 'FJ', NULL, '^\+679\d{7}$', 'Suva', 'Oceania', 'English, Fijian, Hindi', 'UTC+12:00', 'Fijian dollar', 'FJD', '+679', 'Fiji, a country in the South Pacific, is an archipelago of more than 300 islands.'),
('Finland', 'Finlandia', 'FI', NULL, '^\+358\d{8,9}$', 'Helsinki', 'Europe', 'Finnish, Swedish', 'UTC+02:00', 'Euro', 'EUR', '+358', 'Finland is a Northern European nation bordering Sweden, Norway and Russia.')
;


INSERT INTO Countries (EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('France', 'Francja', 'FR', NULL, '^\+33\d{9}$', 'Paris', 'Europe', 'French', 'UTC+01:00', 'Euro', 'EUR', '+33', 'France, in Western Europe, encompasses medieval cities, alpine villages and Mediterranean beaches.'),
('Gabon', 'Gabon', 'GA', NULL, '^\+241\d{7,8}$', 'Libreville', 'Africa', 'French', 'UTC+01:00', 'Central African CFA franc', 'XAF', '+241', 'Gabon is a country along the Atlantic coast of Central Africa, with significant areas of protected parkland.'),
('Gambia', 'Gambia', 'GM', NULL, '^\+220\d{7}$', 'Banjul', 'Africa', 'English', 'UTC+00:00', 'Gambian dalasi', 'GMD', '+220', 'The Gambia is a small West African country, bounded by Senegal, with a narrow Atlantic coastline.'),
('Georgia', 'Gruzja', 'GE', NULL, '^\+995\d{8,9}$', 'Tbilisi', 'Asia', 'Georgian', 'UTC+04:00', 'Georgian lari', 'GEL', '+995', 'Georgia, a country at the intersection of Europe and Asia, is a former Soviet republic that’s home to Caucasus Mountain villages and Black Sea beaches.'),
('Germany', 'Niemcy', 'DE', NULL, '^\+49\d{10}$', 'Berlin', 'Europe', 'German', 'UTC+01:00', 'Euro', 'EUR', '+49', 'Germany is a Western European country with a landscape of forests, rivers, mountain ranges and North Sea beaches.'),
('Ghana', 'Ghana', 'GH', NULL, '^\+233\d{9}$', 'Accra', 'Africa', 'English', 'UTC+00:00', 'Ghanaian cedi', 'GHS', '+233', 'Ghana, a nation on West Africa’s Gulf of Guinea, is known for diverse wildlife, old forts and secluded beaches.'),
('Greece', 'Grecja', 'GR', NULL, '^\+30\d{10}$', 'Athens', 'Europe', 'Greek', 'UTC+02:00', 'Euro', 'EUR', '+30', 'Greece is a country in southeastern Europe with thousands of islands throughout the Aegean and Ionian seas.'),
('Grenada', 'Grenada', 'GD', NULL, '^\+1-473\d{7}$', 'St. George''s', 'North America', 'English', 'UTC-04:00', 'East Caribbean dollar', 'XCD', '+1-473', 'Grenada is a Caribbean country comprising a main island, also called Grenada, and smaller surrounding islands.'),
('Guatemala', 'Gwatemala', 'GT', NULL, '^\+502\d{8}$', 'Guatemala City', 'North America', 'Spanish', 'UTC-06:00', 'Guatemalan quetzal', 'GTQ', '+502', 'Guatemala, a Central American country south of Mexico, is home to volcanoes, rainforests and ancient Mayan sites.'),
('Guinea', 'Gwinea', 'GN', NULL, '^\+224\d{8}$', 'Conakry', 'Africa', 'French', 'UTC+00:00', 'Guinean franc', 'GNF', '+224', 'Guinea, on the West African coast, is known for the Mount Nimba Strict Nature Reserve.'),
('Guinea-Bissau', 'Gwinea Bissau', 'GW', NULL, '^\+245\d{7}$', 'Bissau', 'Africa', 'Portuguese', 'UTC+00:00', 'West African CFA franc', 'XOF', '+245', 'Guinea-Bissau is a tropical country on West Africa’s Atlantic coast known for national parks and wildlife.'),
('Guyana', 'Gujana', 'GY', NULL, '^\+592\d{7}$', 'Georgetown', 'South America', 'English', 'UTC-04:00', 'Guyanese dollar', 'GYD', '+592', 'Guyana, a country on South America’s North Atlantic coast, is defined by its dense rainforest.'),
('Haiti', 'Haiti', 'HT', NULL, '^\+509\d{8}$', 'Port-au-Prince', 'North America', 'French, Haitian Creole', 'UTC-05:00', 'Haitian gourde', 'HTG', '+509', 'Haiti, a Caribbean country that shares the island of Hispaniola with the Dominican Republic to its east.'),
('Honduras', 'Honduras', 'HN', NULL, '^\+504\d{8}$', 'Tegucigalpa', 'North America', 'Spanish', 'UTC-06:00', 'Honduran lempira', 'HNL', '+504', 'Honduras is a Central American country with Caribbean Sea coastlines to the north and the Pacific Ocean to the south.'),
('Hungary', 'Węgry', 'HU', NULL, '^\+36\d{9}$', 'Budapest', 'Europe', 'Hungarian', 'UTC+01:00', 'Hungarian forint', 'HUF', '+36', 'Hungary is a landlocked country in Central Europe.'),
('Iceland', 'Islandia', 'IS', NULL, '^\+354\d{7}$', 'Reykjavik', 'Europe', 'Icelandic', 'UTC+00:00', 'Icelandic króna', 'ISK', '+354', 'Iceland, a Nordic island nation, is defined by its dramatic landscape with volcanoes, geysers, hot springs and lava fields.'),
('India', 'Indie', 'IN', NULL, '^\+91\d{10}$', 'New Delhi', 'Asia', 'Hindi, English', 'UTC+05:30', 'Indian rupee', 'INR', '+91', 'India, a South Asian country, is known for its diverse culture, languages, and history.'),
('Indonesia', 'Indonezja', 'ID', NULL, '^\+62\d{9,10}$', 'Jakarta', 'Asia', 'Indonesian', 'UTC+07:00', 'Indonesian rupiah', 'IDR', '+62', 'Indonesia, a Southeast Asian country, is made up of thousands of volcanic islands and is home to hundreds of ethnic groups speaking many different languages.'),
('Iran', 'Iran', 'IR', NULL, '^\+98\d{10}$', 'Tehran', 'Asia', 'Persian', 'UTC+03:30', 'Iranian rial', 'IRR', '+98', 'Iran, also called Persia, is a country in Western Asia.'),
('Iraq', 'Irak', 'IQ', NULL, '^\+964\d{10}$', 'Baghdad', 'Asia', 'Arabic, Kurdish', 'UTC+03:00', 'Iraqi dinar', 'IQD', '+964', 'Iraq, a country in Western Asia, is known for its rich cultural heritage.'),
('Ireland', 'Irlandia', 'IE', NULL, '^\+353\d{7,9}$', 'Dublin', 'Europe', 'Irish, English', 'UTC+00:00', 'Euro', 'EUR', '+353', 'Ireland is an island in the North Atlantic, known for its lush landscape, castles, and cultural heritage.'),
('Israel', 'Izrael', 'IL', NULL, '^\+972\d{9}$', 'Jerusalem', 'Asia', 'Hebrew, Arabic', 'UTC+02:00', 'Israeli new shekel', 'ILS', '+972', 'Israel, a Middle Eastern country on the Mediterranean Sea, is regarded by Jews, Christians and Muslims as the biblical Holy Land.'),
('Italy', 'Włochy', 'IT', NULL, '^\+39\d{9,10}$', 'Rome', 'Europe', 'Italian', 'UTC+01:00', 'Euro', 'EUR', '+39', 'Italy, a European country with a long Mediterranean coastline, has left a powerful mark on Western culture and cuisine.'),
('Jamaica', 'Jamajka', 'JM', NULL, '^\+1-876\d{7}$', 'Kingston', 'North America', 'English', 'UTC-05:00', 'Jamaican dollar', 'JMD', '+1-876', 'Jamaica is an island country in the Caribbean, known for its vibrant culture, music, and beaches.'),
('Japan', 'Japonia', 'JP', NULL, '^\+81\d{9}$', 'Tokyo', 'Asia', 'Japanese', 'UTC+09:00', 'Japanese yen', 'JPY', '+81', 'Japan is an island country in East Asia, known for its dense cities, imperial palaces, mountainous national parks, and thousands of shrines and temples.'),
('Jordan', 'Jordania', 'JO', NULL, '^\+962\d{8,9}$', 'Amman', 'Asia', 'Arabic', 'UTC+02:00', 'Jordanian dinar', 'JOD', '+962', 'Jordan is an Arab nation on the east bank of the Jordan River, defined by ancient monuments, nature reserves, and seaside resorts.'),
('Kazakhstan', 'Kazachstan', 'KZ', NULL, '^\+7\d{9,10}$', 'Nur-Sultan', 'Asia', 'Kazakh, Russian', 'UTC+05:00 to UTC+06:00', 'Kazakhstani tenge', 'KZT', '+7', 'Kazakhstan, a Central Asian country and former Soviet republic, extends from the Caspian Sea in the west to the Altai Mountains at its eastern border with China and Russia.')
;


INSERT INTO Countries (EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('Kenya', 'Kenia', 'KE', NULL, '^\+254\d{9}$', 'Nairobi', 'Africa', 'Swahili, English', 'UTC+03:00', 'Kenyan shilling', 'KES', '+254', 'Kenya is a country in East Africa with coastline on the Indian Ocean.'),
('Kiribati', 'Kiribati', 'KI', NULL, '^\+686\d{5}$', 'Tarawa', 'Oceania', 'English, Gilbertese', 'UTC+12:00 to UTC+14:00', 'Australian dollar', 'AUD', '+686', 'Kiribati is a country in the central Pacific Ocean.'),
('Korea, North', 'Korea Północna', 'KP', NULL, '^\+850\d{8,9}$', 'Pyongyang', 'Asia', 'Korean', 'UTC+09:00', 'North Korean won', 'KPW', '+850', 'North Korea, officially the Democratic People''s Republic of Korea, is a country in East Asia constituting the northern part of the Korean Peninsula.'),
('Kuwait', 'Kuwejt', 'KW', NULL, '^\+965\d{8}$', 'Kuwait City', 'Asia', 'Arabic', 'UTC+03:00', 'Kuwaiti dinar', 'KWD', '+965', 'Kuwait is a country in Western Asia.'),
('Kyrgyzstan', 'Kirgistan', 'KG', NULL, '^\+996\d{9}$', 'Bishkek', 'Asia', 'Kyrgyz, Russian', 'UTC+06:00', 'Kyrgyzstani som', 'KGS', '+996', 'Kyrgyzstan is a rugged Central Asian country along the Silk Road.'),
('Laos', 'Laos', 'LA', NULL, '^\+856\d{8,9}$', 'Vientiane', 'Asia', 'Lao', 'UTC+07:00', 'Lao kip', 'LAK', '+856', 'Laos is a Southeast Asian country traversed by the Mekong River and known for mountainous terrain.'),
('Latvia', 'Łotwa', 'LV', NULL, '^\+371\d{8}$', 'Riga', 'Europe', 'Latvian', 'UTC+02:00', 'Euro', 'EUR', '+371', 'Latvia is a country on the Baltic Sea between Lithuania and Estonia.'),
('Lebanon', 'Liban', 'LB', NULL, '^\+961\d{7,8}$', 'Beirut', 'Asia', 'Arabic', 'UTC+02:00', 'Lebanese pound', 'LBP', '+961', 'Lebanon, a country in Western Asia, is known for its rich history and cultural heritage.'),
('Lesotho', 'Lesotho', 'LS', NULL, '^\+266\d{8}$', 'Maseru', 'Africa', 'Sesotho, English', 'UTC+02:00', 'Lesotho loti', 'LSL', '+266', 'Lesotho, a high-altitude, landlocked kingdom encircled by South Africa, is crisscrossed by a network of rivers and mountain ranges including the 3,482m-high peak of Thabana Ntlenyana.'),
('Liberia', 'Liberia', 'LR', NULL, '^\+231\d{7,8}$', 'Monrovia', 'Africa', 'English', 'UTC+00:00', 'Liberian dollar', 'LRD', '+231', 'Liberia, a country in West Africa, is known for its rich history as Africa''s first republic.'),
('Libya', 'Libia', 'LY', NULL, '^\+218\d{8,9}$', 'Tripoli', 'Africa', 'Arabic', 'UTC+02:00', 'Libyan dinar', 'LYD', '+218', 'Libya is a country in North Africa, known for its vast desert and Mediterranean coastline.'),
('Liechtenstein', 'Liechtenstein', 'LI', NULL, '^\+423\d{7}$', 'Vaduz', 'Europe', 'German', 'UTC+01:00', 'Swiss franc', 'CHF', '+423', 'Liechtenstein is a German-speaking, 25km-long principality between Austria and Switzerland.'),
('Lithuania', 'Litwa', 'LT', NULL, '^\+370\d{8}$', 'Vilnius', 'Europe', 'Lithuanian', 'UTC+02:00', 'Euro', 'EUR', '+370', 'Lithuania, a country in the Baltic region of Europe, is known for its medieval history.'),
('Luxembourg', 'Luksemburg', 'LU', NULL, '^\+352\d{8}$', 'Luxembourg City', 'Europe', 'Luxembourgish, French, German', 'UTC+01:00', 'Euro', 'EUR', '+352', 'Luxembourg is a small European country, surrounded by Belgium, France and Germany.'),
('Madagascar', 'Madagaskar', 'MG', NULL, '^\+261\d{9}$', 'Antananarivo', 'Africa', 'Malagasy, French', 'UTC+03:00', 'Malagasy ariary', 'MGA', '+261', 'Madagascar, an island country in the Indian Ocean, is known for its unique wildlife.'),
('Malawi', 'Malawi', 'MW', NULL, '^\+265\d{9}$', 'Lilongwe', 'Africa', 'English, Chichewa', 'UTC+02:00', 'Malawian kwacha', 'MWK', '+265', 'Malawi, a landlocked country in southeastern Africa, is defined by its topography of highlands split by the Great Rift Valley and enormous Lake Malawi.'),
('Malaysia', 'Malezja', 'MY', NULL, '^\+60\d{8,9}$', 'Kuala Lumpur', 'Asia', 'Malay', 'UTC+08:00', 'Malaysian ringgit', 'MYR', '+60', 'Malaysia is a Southeast Asian country occupying parts of the Malay Peninsula and the island of Borneo.'),
('Maldives', 'Malediwy', 'MV', NULL, '^\+960\d{7}$', 'Malé', 'Asia', 'Dhivehi', 'UTC+05:00', 'Maldivian rufiyaa', 'MVR', '+960', 'The Maldives, a tropical paradise in the Indian Ocean, is known for its beaches, blue lagoons and extensive coral reefs.'),
('Mali', 'Mali', 'ML', NULL, '^\+223\d{8}$', 'Bamako', 'Africa', 'French', 'UTC+00:00', 'West African CFA franc', 'XOF', '+223', 'Mali, a landlocked country in West Africa, is known for its rich history and cultural heritage.'),
('Malta', 'Malta', 'MT', NULL, '^\+356\d{8}$', 'Valletta', 'Europe', 'Maltese, English', 'UTC+01:00', 'Euro', 'EUR', '+356', 'Malta is a Southern European island country consisting of an archipelago in the Mediterranean Sea.'),
('Marshall Islands', 'Wyspy Marshalla', 'MH', NULL, '^\+692\d{7}$', 'Majuro', 'Oceania', 'Marshallese, English', 'UTC+12:00', 'United States dollar', 'USD', '+692', 'The Marshall Islands, a sprawling chain of volcanic islands and coral atolls in the central Pacific Ocean, is known for its marine life.'),
('Mauritania', 'Mauretania', 'MR', NULL, '^\+222\d{8}$', 'Nouakchott', 'Africa', 'Arabic', 'UTC+00:00', 'Mauritanian ouguiya', 'MRU', '+222', 'Mauritania, a country in Northwest Africa, is known for its Saharan landscapes and rich cultural history.'),
('Mauritius', 'Mauritius', 'MU', NULL, '^\+230\d{7}$', 'Port Louis', 'Africa', 'English, French', 'UTC+04:00', 'Mauritian rupee', 'MUR', '+230', 'Mauritius, an Indian Ocean island nation, is known for its beaches, lagoons and reefs.'),
('Mexico', 'Meksyk', 'MX', NULL, '^\+52\d{10}$', 'Mexico City', 'North America', 'Spanish', 'UTC-06:00 to UTC-08:00', 'Mexican peso', 'MXN', '+52', 'Mexico is a country in the southern portion of North America, known for its rich culture and history.'),
('Micronesia', 'Mikronezja', 'FM', NULL, '^\+691\d{7}$', 'Palikir', 'Oceania', 'English', 'UTC+10:00', 'United States dollar', 'USD', '+691', 'Micronesia is a subregion of Oceania, composed of thousands of small islands in the western Pacific Ocean.'),
('Moldova', 'Mołdawia', 'MD', NULL, '^\+373\d{8}$', 'Chișinău', 'Europe', 'Romanian', 'UTC+02:00', 'Moldovan leu', 'MDL', '+373', 'Moldova, an Eastern European country and former Soviet republic, has varied terrain including forests, rocky hills and vineyards.'),
('Monaco', 'Monako', 'MC', NULL, '^\+377\d{8}$', 'Monaco', 'Europe', 'French', 'UTC+01:00', 'Euro', 'EUR', '+377', 'Monaco, a tiny independent city-state on France’s Mediterranean coastline, is known for its upscale casinos, yacht-lined harbor and prestigious Grand Prix motor race.')
;

INSERT INTO Countries (EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('Mongolia', 'Mongolia', 'MN', NULL, '^\+976\d{8}$', 'Ulaanbaatar', 'Asia', 'Mongolian', 'UTC+08:00', 'Mongolian tögrög', 'MNT', '+976', 'Mongolia, a landlocked country in East Asia, is known for its vast, rugged expanses and nomadic culture.'),
('Montenegro', 'Czarnogóra', 'ME', NULL, '^\+382\d{8}$', 'Podgorica', 'Europe', 'Montenegrin', 'UTC+01:00', 'Euro', 'EUR', '+382', 'Montenegro is a Balkan country with rugged mountains, medieval villages and a narrow strip of beaches along its Adriatic coastline.'),
('Morocco', 'Maroko', 'MA', NULL, '^\+212\d{9}$', 'Rabat', 'Africa', 'Arabic', 'UTC+00:00', 'Moroccan dirham', 'MAD', '+212', 'Morocco, a North African country bordering the Atlantic Ocean and Mediterranean Sea, is distinguished by its Berber, Arabian and European cultural influences.'),
('Mozambique', 'Mozambik', 'MZ', NULL, '^\+258\d{9}$', 'Maputo', 'Africa', 'Portuguese', 'UTC+02:00', 'Mozambican metical', 'MZN', '+258', 'Mozambique is a southern African nation whose long Indian Ocean coastline is dotted with popular beaches.'),
('Myanmar', 'Mjanma', 'MM', NULL, '^\+95\d{8,9}$', 'Naypyidaw', 'Asia', 'Burmese', 'UTC+06:30', 'Burmese kyat', 'MMK', '+95', 'Myanmar (formerly Burma) is a Southeast Asian nation of more than 100 ethnic groups, bordering India, Bangladesh, China, Laos and Thailand.'),
('Namibia', 'Namibia', 'NA', NULL, '^\+264\d{8}$', 'Windhoek', 'Africa', 'English', 'UTC+02:00', 'Namibian dollar', 'NAD', '+264', 'Namibia, a country in southwest Africa, is distinguished by the Namib Desert along its Atlantic Ocean coast.'),
('Nauru', 'Nauru', 'NR', NULL, '^\+674\d{7}$', 'Yaren', 'Oceania', 'Nauruan, English', 'UTC+12:00', 'Australian dollar', 'AUD', '+674', 'Nauru is a tiny island country in Micronesia, northeast of Australia.'),
('Nepal', 'Nepal', 'NP', NULL, '^\+977\d{8,9}$', 'Kathmandu', 'Asia', 'Nepali', 'UTC+05:45', 'Nepalese rupee', 'NPR', '+977', 'Nepal, a Himalayan nation, is known for its temples and Himalayan mountains, including Mount Everest.'),
('Netherlands', 'Holandia', 'NL', NULL, '^\+31\d{9}$', 'Amsterdam', 'Europe', 'Dutch', 'UTC+01:00', 'Euro', 'EUR', '+31', 'The Netherlands is a country in Northwestern Europe known for its flat landscape of canals, tulip fields, windmills and cycling routes.'),
('New Zealand', 'Nowa Zelandia', 'NZ', NULL, '^\+64\d{8,9}$', 'Wellington', 'Oceania', 'English, Māori', 'UTC+12:00', 'New Zealand dollar', 'NZD', '+64', 'New Zealand is a country in the southwestern Pacific Ocean consisting of 2 main islands, both marked by volcanoes and glaciation.'),
('Nicaragua', 'Nikaragua', 'NI', NULL, '^\+505\d{8}$', 'Managua', 'North America', 'Spanish', 'UTC-06:00', 'Nicaraguan córdoba', 'NIO', '+505', 'Nicaragua, set between the Pacific Ocean and the Caribbean Sea, is a Central American nation known for its dramatic terrain of lakes, volcanoes and beaches.'),
('Niger', 'Niger', 'NE', NULL, '^\+227\d{8}$', 'Niamey', 'Africa', 'French', 'UTC+01:00', 'West African CFA franc', 'XOF', '+227', 'Niger is a landlocked country in West Africa named after the Niger River.'),
('Nigeria', 'Nigeria', 'NG', NULL, '^\+234\d{8,10}$', 'Abuja', 'Africa', 'English', 'UTC+01:00', 'Nigerian naira', 'NGN', '+234', 'Nigeria is an African country on the Gulf of Guinea known for its natural landmarks and wildlife reserves.'),
('North Macedonia', 'Macedonia Północna', 'MK', NULL, '^\+389\d{8}$', 'Skopje', 'Europe', 'Macedonian', 'UTC+01:00', 'Macedonian denar', 'MKD', '+389', 'North Macedonia is a Balkan nation of mountains, lakes and ancient towns with Ottoman and European architecture.'),
('Norway', 'Norwegia', 'NO', NULL, '^\+47\d{8}$', 'Oslo', 'Europe', 'Norwegian', 'UTC+01:00', 'Norwegian krone', 'NOK', '+47', 'Norway is a Scandinavian country encompassing mountains, glaciers and deep coastal fjords.'),
('Oman', 'Oman', 'OM', NULL, '^\+968\d{8}$', 'Muscat', 'Asia', 'Arabic', 'UTC+04:00', 'Omani rial', 'OMR', '+968', 'Oman is an Arab country on the southeastern coast of the Arabian Peninsula in Western Asia.'),
('Pakistan', 'Pakistan', 'PK', NULL, '^\+92\d{9,10}$', 'Islamabad', 'Asia', 'Urdu, English', 'UTC+05:00', 'Pakistani rupee', 'PKR', '+92', 'Pakistan, officially the Islamic Republic of Pakistan, is a country in South Asia.'),
('Palau', 'Palau', 'PW', NULL, '^\+680\d{7}$', 'Ngerulmud', 'Oceania', 'Palauan, English', 'UTC+09:00', 'United States dollar', 'USD', '+680', 'Palau is an archipelago of over 500 islands, part of the Micronesia region in the western Pacific Ocean.'),
('Panama', 'Panama', 'PA', NULL, '^\+507\d{8}$', 'Panama City', 'North America', 'Spanish', 'UTC-05:00', 'Panamanian balboa, United States dollar', 'PAB, USD', '+507', 'Panama is a country on the isthmus linking Central and South America, known for the Panama Canal.'),
('Papua New Guinea', 'Papua-Nowa Gwinea', 'PG', NULL, '^\+675\d{8}$', 'Port Moresby', 'Oceania', 'English, Tok Pisin, Hiri Motu', 'UTC+10:00', 'Papua New Guinean kina', 'PGK', '+675', 'Papua New Guinea is an Oceanian country that occupies the eastern half of the island of New Guinea and its offshore islands in Melanesia.'),
('Paraguay', 'Paragwaj', 'PY', NULL, '^\+595\d{8,9}$', 'Asunción', 'South America', 'Spanish, Guarani', 'UTC-04:00', 'Paraguayan guaraní', 'PYG', '+595', 'Paraguay, a landlocked country between Argentina, Brazil and Bolivia, is known for its chipa bread and subtropical forests.'),
('Peru', 'Peru', 'PE', NULL, '^\+51\d{8,9}$', 'Lima', 'South America', 'Spanish', 'UTC-05:00', 'Peruvian sol', 'PEN', '+51', 'Peru is a country in South America that''s home to a section of Amazon rainforest and Machu Picchu, an ancient Incan city high in the Andes mountains.'),
('Philippines', 'Filipiny', 'PH', NULL, '^\+63\d{10}$', 'Manila', 'Asia', 'Filipino, English', 'UTC+08:00', 'Philippine peso', 'PHP', '+63', 'The Philippines is an archipelago in Southeast Asia, known for its beaches, volcanoes, and rich biodiversity.'),
('Poland', 'Polska', 'PL', NULL, '^\+48\d{9}$', 'Warsaw', 'Europe', 'Polish', 'UTC+01:00', 'Polish złoty', 'PLN', '+48', 'Poland is a country located in Central Europe known for its medieval architecture and Jewish heritage.'),
('Portugal', 'Portugalia', 'PT', NULL, '^\+351\d{9}$', 'Lisbon', 'Europe', 'Portuguese', 'UTC+00:00', 'Euro', 'EUR', '+351', 'Portugal is a southern European country on the Iberian Peninsula, bordering Spain.'),
('Qatar', 'Katar', 'QA', NULL, '^\+974\d{8}$', 'Doha', 'Asia', 'Arabic', 'UTC+03:00', 'Qatari riyal', 'QAR', '+974', 'Qatar is a peninsular Arab country whose terrain comprises arid desert and a long Persian (Arab) Gulf shoreline of beaches and dunes.')
;

INSERT INTO Countries (EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('Romania', 'Rumunia', 'RO', NULL, '^\+40\d{9}$', 'Bucharest', 'Europe', 'Romanian', 'UTC+02:00', 'Romanian leu', 'RON', '+40', 'Romania is a southeastern European country known for the forested region of Transylvania, ringed by the Carpathian Mountains.'),
('Russia', 'Rosja', 'RU', NULL, '^\+7\d{10}$', 'Moscow', 'Europe, Asia', 'Russian', 'UTC+03:00 to UTC+12:00', 'Russian ruble', 'RUB', '+7', 'Russia, the world’s largest nation, borders European and Asian countries as well as the Pacific and Arctic oceans.'),
('Rwanda', 'Rwanda', 'RW', NULL, '^\+250\d{9}$', 'Kigali', 'Africa', 'Kinyarwanda, French, English', 'UTC+02:00', 'Rwandan franc', 'RWF', '+250', 'Rwanda, a landlocked East African country, has a green, mountainous landscape.'),
('Saint Kitts and Nevis', 'Saint Kitts i Nevis', 'KN', NULL, '^\+1-869\d{7}$', 'Basseterre', 'North America', 'English', 'UTC-04:00', 'East Caribbean dollar', 'XCD', '+1-869', 'Saint Kitts and Nevis is a dual-island nation situated between the Atlantic Ocean and Caribbean Sea.'),
('Saint Lucia', 'Saint Lucia', 'LC', NULL, '^\+1-758\d{7}$', 'Castries', 'North America', 'English', 'UTC-04:00', 'East Caribbean dollar', 'XCD', '+1-758', 'Saint Lucia is an Eastern Caribbean island nation with a pair of dramatically tapered mountains, the Pitons, on its west coast.'),
('Saint Vincent and the Grenadines', 'Saint Vincent i Grenadyny', 'VC', NULL, '^\+1-784\d{7}$', 'Kingstown', 'North America', 'English', 'UTC-04:00', 'East Caribbean dollar', 'XCD', '+1-784', 'Saint Vincent and the Grenadines is a Caribbean nation comprising a main island, Saint Vincent, and a chain of smaller islands.'),
('Samoa', 'Samoa', 'WS', NULL, '^\+685\d{5,6}$', 'Apia', 'Oceania', 'Samoan, English', 'UTC+13:00', 'Samoan tālā', 'WST', '+685', 'Samoa is a country comprising the westernmost group of the Samoan Islands, in Polynesia.'),
('San Marino', 'San Marino', 'SM', NULL, '^\+378\d{8}$', 'San Marino', 'Europe', 'Italian', 'UTC+01:00', 'Euro', 'EUR', '+378', 'San Marino is a mountainous microstate surrounded by north-central Italy.'),
('Sao Tome and Principe', 'Wyspy Świętego Tomasza i Książęca', 'ST', NULL, '^\+239\d{7}$', 'São Tomé', 'Africa', 'Portuguese', 'UTC+00:00', 'São Tomé and Príncipe dobra', 'STN', '+239', 'São Tomé and Príncipe is a Central African nation consisting of two archipelagos around the two main islands.'),
('Saudi Arabia', 'Arabia Saudyjska', 'SA', NULL, '^\+966\d{8,9}$', 'Riyadh', 'Asia', 'Arabic', 'UTC+03:00', 'Saudi riyal', 'SAR', '+966', 'Saudi Arabia is a desert country encompassing most of the Arabian Peninsula, with Red Sea and Persian (Arabian) Gulf coastlines.'),
('Senegal', 'Senegal', 'SN', NULL, '^\+221\d{8,9}$', 'Dakar', 'Africa', 'French', 'UTC+00:00', 'West African CFA franc', 'XOF', '+221', 'Senegal is a country on Africa’s west coast known for its French colonial heritage and natural attractions.'),
('Serbia', 'Serbia', 'RS', NULL, '^\+381\d{8,9}$', 'Belgrade', 'Europe', 'Serbian', 'UTC+01:00', 'Serbian dinar', 'RSD', '+381', 'Serbia is a country on southeast Europe’s Balkan Peninsula with northern plateaus and mountains with ski resorts to the south.'),
('Seychelles', 'Seszele', 'SC', NULL, '^\+248\d{6}$', 'Victoria', 'Africa', 'French, English, Seychellois Creole', 'UTC+04:00', 'Seychellois rupee', 'SCR', '+248', 'Seychelles is an archipelago of 115 islands in the Indian Ocean, off East Africa.'),
('Sierra Leone', 'Sierra Leone', 'SL', NULL, '^\+232\d{8,9}$', 'Freetown', 'Africa', 'English', 'UTC+00:00', 'Sierra Leonean leone', 'SLL', '+232', 'Sierra Leone is a country in West Africa, on the Atlantic Ocean.'),
('Singapore', 'Singapur', 'SG', NULL, '^\+65\d{8}$', 'Singapore', 'Asia', 'English, Malay, Mandarin, Tamil', 'UTC+08:00', 'Singapore dollar', 'SGD', '+65', 'Singapore is a global financial hub and island city-state in Southeast Asia.'),
('Slovakia', 'Słowacja', 'SK', NULL, '^\+421\d{8,9}$', 'Bratislava', 'Europe', 'Slovak', 'UTC+01:00', 'Euro', 'EUR', '+421', 'Slovakia is a central European country known for its dramatic natural landscape and many castles.'),
('Slovenia', 'Słowenia', 'SI', NULL, '^\+386\d{8,9}$', 'Ljubljana', 'Europe', 'Slovene', 'UTC+01:00', 'Euro', 'EUR', '+386', 'Slovenia is a country in Central Europe known for its mountains, ski resorts and lakes.'),
('Solomon Islands', 'Wyspy Salomona', 'SB', NULL, '^\+677\d{5,6}$', 'Honiara', 'Oceania', 'English', 'UTC+11:00', 'Solomon Islands dollar', 'SBD', '+677', 'The Solomon Islands, a nation of hundreds of islands in the South Pacific, has many WWII-era sites.'),
('Somalia', 'Somalia', 'SO', NULL, '^\+252\d{8,9}$', 'Mogadishu', 'Africa', 'Somali, Arabic', 'UTC+03:00', 'Somali shilling', 'SOS', '+252', 'Somalia is a country located in the Horn of Africa.'),
('South Africa', 'Republika Południowej Afryki', 'ZA', NULL, '^\+27\d{9}$', 'Pretoria', 'Africa', 'Zulu, Xhosa, Afrikaans, English', 'UTC+02:00', 'South African rand', 'ZAR', '+27', 'South Africa is a country on the southernmost tip of the African continent, marked by several distinct ecosystems.'),
('South Korea', 'Korea Południowa', 'KR', NULL, '^\+82\d{9}$', 'Seoul', 'Asia', 'Korean', 'UTC+09:00', 'South Korean won', 'KRW', '+82', 'South Korea, an East Asian nation on the southern half of the Korean Peninsula, shares one of the world’s most heavily militarized borders with North Korea.'),
('South Sudan', 'Sudan Południowy', 'SS', NULL, '^\+211\d{8,9}$', 'Juba', 'Africa', 'English', 'UTC+03:00', 'South Sudanese pound', 'SSP', '+211', 'South Sudan, officially known as the Republic of South Sudan, is a landlocked country in East-Central Africa.'),
('Spain', 'Hiszpania', 'ES', NULL, '^\+34\d{9}$', 'Madrid', 'Europe', 'Spanish', 'UTC+01:00', 'Euro', 'EUR', '+34', 'Spain, a country on Europe’s Iberian Peninsula, includes 17 autonomous regions with diverse geography and cultures.'),
('Sri Lanka', 'Sri Lanka', 'LK', NULL, '^\+94\d{8,9}$', 'Sri Jayawardenepura Kotte', 'Asia', 'Sinhala, Tamil', 'UTC+05:30', 'Sri Lankan rupee', 'LKR', '+94', 'Sri Lanka, an island nation south of India in the Indian Ocean, has diverse landscapes and rich history.'),
('Sudan', 'Sudan', 'SD', NULL, '^\+249\d{8,9}$', 'Khartoum', 'Africa', 'Arabic, English', 'UTC+02:00', 'Sudanese pound', 'SDG', '+249', 'Sudan, in northeastern Africa, is known for its ancient Nubian pyramids and the Nile River.'),
('Suriname', 'Surinam', 'SR', NULL, '^\+597\d{7}$', 'Paramaribo', 'South America', 'Dutch', 'UTC-03:00', 'Surinamese dollar', 'SRD', '+597', 'Suriname, a small country on the northeastern coast of South America, is defined by vast swaths of tropical rainforest.')
;


INSERT INTO Countries (EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('Sweden', 'Szwecja', 'SE', NULL, '^\+46\d{7,9}$', 'Stockholm', 'Europe', 'Swedish', 'UTC+01:00', 'Swedish krona', 'SEK', '+46', 'Sweden is a Scandinavian nation with thousands of coastal islands and inland lakes, along with vast boreal forests and glaciated mountains.'),
('Switzerland', 'Szwajcaria', 'CH', NULL, '^\+41\d{8,9}$', 'Bern', 'Europe', 'German, French, Italian, Romansh', 'UTC+01:00', 'Swiss franc', 'CHF', '+41', 'Switzerland is a mountainous Central European country, home to numerous lakes, villages and the high peaks of the Alps.'),
('Syria', 'Syria', 'SY', NULL, '^\+963\d{8,9}$', 'Damascus', 'Asia', 'Arabic', 'UTC+02:00', 'Syrian pound', 'SYP', '+963', 'Syria is a country in Western Asia, bordering Lebanon, Turkey, Iraq, Jordan, Israel, and Palestine.'),
('Taiwan', 'Tajwan', 'TW', NULL, '^\+886\d{8,9}$', 'Taipei', 'Asia', 'Mandarin Chinese', 'UTC+08:00', 'New Taiwan dollar', 'TWD', '+886', 'Taiwan is a small island nation east of China with modern cities, traditional Chinese temples, hot springs resorts, and dramatic mountainous terrain.'),
('Tajikistan', 'Tadżykistan', 'TJ', NULL, '^\+992\d{8,9}$', 'Dushanbe', 'Asia', 'Tajik', 'UTC+05:00', 'Tajikistani somoni', 'TJS', '+992', 'Tajikistan is a Central Asian country surrounded by Afghanistan, China, Kyrgyzstan and Uzbekistan.'),
('Tanzania', 'Tanzania', 'TZ', NULL, '^\+255\d{9}$', 'Dodoma', 'Africa', 'Swahili, English', 'UTC+03:00', 'Tanzanian shilling', 'TZS', '+255', 'Tanzania is an East African country known for its vast wilderness areas, including the plains of Serengeti National Park and Kilimanjaro National Park.'),
('Thailand', 'Tajlandia', 'TH', NULL, '^\+66\d{8,9}$', 'Bangkok', 'Asia', 'Thai', 'UTC+07:00', 'Thai baht', 'THB', '+66', 'Thailand is a Southeast Asian country known for tropical beaches, opulent royal palaces, ancient ruins, and ornate temples displaying figures of Buddha.'),
('Timor-Leste', 'Timor Wschodni', 'TL', NULL, '^\+670\d{7}$', 'Dili', 'Asia', 'Tetum, Portuguese', 'UTC+09:00', 'United States dollar', 'USD', '+670', 'Timor-Leste, or East Timor, is a Southeast Asian nation occupying half the island of Timor.'),
('Togo', 'Togo', 'TG', NULL, '^\+228\d{8}$', 'Lomé', 'Africa', 'French', 'UTC+00:00', 'West African CFA franc', 'XOF', '+228', 'Togo is a West African nation on the Gulf of Guinea, known for its palm-lined beaches and hilltop villages.'),
('Tonga', 'Tonga', 'TO', NULL, '^\+676\d{5}$', 'Nuku''alofa', 'Oceania', 'Tongan, English', 'UTC+13:00', 'Tongan paʻanga', 'TOP', '+676', 'Tonga is a Polynesian kingdom of more than 170 South Pacific islands, many uninhabited, most lined in white beaches and coral reefs and covered with tropical rainforest.'),
('Trinidad and Tobago', 'Trynidad i Tobago', 'TT', NULL, '^\+1-868\d{7}$', 'Port of Spain', 'North America', 'English', 'UTC-04:00', 'Trinidad and Tobago dollar', 'TTD', '+1-868', 'Trinidad and Tobago is a dual-island Caribbean nation near Venezuela with distinctive Creole traditions and cuisines.'),
('Tunisia', 'Tunezja', 'TN', NULL, '^\+216\d{8}$', 'Tunis', 'Africa', 'Arabic', 'UTC+01:00', 'Tunisian dinar', 'TND', '+216', 'Tunisia is a North African country bordering the Mediterranean Sea and Sahara Desert.'),
('Turkey', 'Turcja', 'TR', NULL, '^\+90\d{10}$', 'Ankara', 'Asia, Europe', 'Turkish', 'UTC+03:00', 'Turkish lira', 'TRY', '+90', 'Turkey is a nation straddling eastern Europe and western Asia with cultural connections to ancient Greek, Persian, Roman, Byzantine and Ottoman empires.'),
('Turkmenistan', 'Turkmenistan', 'TM', NULL, '^\+993\d{8}$', 'Ashgabat', 'Asia', 'Turkmen', 'UTC+05:00', 'Turkmenistan manat', 'TMT', '+993', 'Turkmenistan is a country in Central Asia bordered by the Caspian Sea and largely covered by the Karakum Desert.'),
('Tuvalu', 'Tuvalu', 'TV', NULL, '^\+688\d{6}$', 'Funafuti', 'Oceania', 'Tuvaluan, English', 'UTC+12:00', 'Tuvaluan dollar, Australian dollar', 'TVD, AUD', '+688', 'Tuvalu is a small island nation in the Pacific Ocean formerly known as the Ellice Islands.'),
('Uganda', 'Uganda', 'UG', NULL, '^\+256\d{9}$', 'Kampala', 'Africa', 'English, Swahili', 'UTC+03:00', 'Ugandan shilling', 'UGX', '+256', 'Uganda is a landlocked country in East Africa whose diverse landscape encompasses the snow-capped Rwenzori Mountains and immense Lake Victoria.'),
('Ukraine', 'Ukraina', 'UA', NULL, '^\+380\d{9}$', 'Kyiv', 'Europe', 'Ukrainian', 'UTC+02:00', 'Ukrainian hryvnia', 'UAH', '+380', 'Ukraine is a large country in Eastern Europe known for its Orthodox churches, Black Sea coastline and forested mountains.'),
('United Arab Emirates', 'Zjednoczone Emiraty Arabskie', 'AE', NULL, '^\+971\d{9}$', 'Abu Dhabi', 'Asia', 'Arabic', 'UTC+04:00', 'United Arab Emirates dirham', 'AED', '+971', 'The UAE is a federation of seven emirates including Dubai and Abu Dhabi.'),
('United Kingdom', 'Zjednoczone Królestwo', 'GB', NULL, '^\+44\d{10}$', 'London', 'Europe', 'English', 'UTC+00:00', 'Pound sterling', 'GBP', '+44', 'The United Kingdom, made up of England, Scotland, Wales and Northern Ireland, is an island nation in northwestern Europe.'),
('United States', 'Stany Zjednoczone', 'US', NULL, '^\+1\d{10}$', 'Washington, D.C.', 'North America', 'English', 'UTC-05:00 to UTC-10:00', 'United States dollar', 'USD', '+1', 'The United States of America is a large country in North America, often known as "the USA", "US", "United States", or simply "the States".'),
('Uruguay', 'Urugwaj', 'UY', NULL, '^\+598\d{8}$', 'Montevideo', 'South America', 'Spanish', 'UTC-03:00', 'Uruguayan peso', 'UYU', '+598', 'Uruguay is a South American country known for its verdant interior and beach-lined coast.')
;


INSERT INTO Countries (EnglishName, PolishName, IsoCode, Icon, RegexPhone, Capital, Continent, OfficialLanguage, TimeZone, Currency, CurrencyCode, CallingCode, Description)
VALUES
('Uzbekistan', 'Uzbekistan', 'UZ', NULL, '^\+998\d{9}$', 'Tashkent', 'Asia', 'Uzbek', 'UTC+05:00', 'Uzbekistani soʻm', 'UZS', '+998', 'Uzbekistan is a Central Asian nation and former Soviet republic. It''s known for its mosques, mausoleums and other sites linked to the Silk Road.'),
('Vanuatu', 'Vanuatu', 'VU', NULL, '^\+678\d{7}$', 'Port Vila', 'Oceania', 'Bislama, English, French', 'UTC+11:00', 'Vanuatu vatu', 'VUV', '+678', 'Vanuatu is a South Pacific Ocean nation made up of roughly 80 islands.'),
('Vatican City', 'Watykan', 'VA', NULL, '^\+379\d{8}$', 'Vatican City', 'Europe', 'Italian', 'UTC+01:00', 'Euro', 'EUR', '+379', 'Vatican City is the headquarters of the Roman Catholic Church, and the Pope''s residence.'),
('Venezuela', 'Wenezuela', 'VE', NULL, '^\+58\d{10}$', 'Caracas', 'South America', 'Spanish', 'UTC-04:00', 'Venezuelan bolívar', 'VES', '+58', 'Venezuela is a country on the northern coast of South America with diverse natural attractions.'),
('Vietnam', 'Wietnam', 'VN', NULL, '^\+84\d{9,10}$', 'Hanoi', 'Asia', 'Vietnamese', 'UTC+07:00', 'Vietnamese đồng', 'VND', '+84', 'Vietnam is a Southeast Asian country known for its beaches, rivers, Buddhist pagodas and bustling cities.'),
('Yemen', 'Jemen', 'YE', NULL, '^\+967\d{8,9}$', 'Sana''a', 'Asia', 'Arabic', 'UTC+03:00', 'Yemeni rial', 'YER', '+967', 'Yemen is a country at the southern end of the Arabian Peninsula in Western Asia.'),
('Zambia', 'Zambia', 'ZM', NULL, '^\+260\d{8,9}$', 'Lusaka', 'Africa', 'English', 'UTC+02:00', 'Zambian kwacha', 'ZMW', '+260', 'Zambia is a landlocked country in southern Africa, known for its rugged terrain and diverse wildlife, with many parks and safari areas.'),
('Zimbabwe', 'Zimbabwe', 'ZW', NULL, '^\+263\d{9}$', 'Harare', 'Africa', 'English, Shona, Ndebele', 'UTC+02:00', 'Zimbabwean dollar', 'ZWL', '+263', 'Zimbabwe is a landlocked country in southern Africa known for its dramatic landscape and diverse wildlife, much of it within parks, reserves and safari areas.'),
('Palestine', 'Palestyna', 'PS', NULL, '^\+970\d{8,9}$', 'Ramallah', 'Asia', 'Arabic', 'UTC+02:00', 'Israeli new shekel', 'ILS', '+970', 'Palestine, recognized officially as the State of Palestine by the United Nations, is a de jure sovereign state in Western Asia.'),
('Western Sahara', 'Sahara Zachodnia', 'EH', NULL, '^\+212\d{9}$', 'Laayoune', 'Africa', 'Arabic, Spanish', 'UTC+00:00', 'Moroccan dirham', 'MAD', '+212', 'Western Sahara is a disputed territory on the northwest coast of Africa.'),
('Kosovo', 'Kosowo', 'XK', NULL, '^\+383\d{8}$', 'Pristina', 'Europe', 'Albanian, Serbian', 'UTC+01:00', 'Euro', 'EUR', '+383', 'Kosovo is a partially recognized country in Southeast Europe, subject to a territorial dispute with Serbia.')
;


select RegexPhone, count(*) from Countries group by RegexPhone having count(*) > 1

select * from Countries where RegexPhone in (
'^\+1\d{10}$',
'^\+212\d{9}$'
)

--delete top(1) Countries where Id = 90
